# Generated by Django 2.2.4 on 2022-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='visited_by',
            field=models.ManyToManyField(related_name='visitors', to='FirstApp.User'),
        ),
    ]
